library(openxlsx)
#Plotting life tables
SPWL_Female_NS<-read.xlsx("data/base-life-tables.xlsx", sheet = 1)
SPWL_Female_S<-read.xlsx("data/base-life-tables.xlsx", sheet = 2)
SPWL_Male_NS<-read.xlsx("data/base-life-tables.xlsx", sheet = 3)
SPWL_Male_S<-read.xlsx("data/base-life-tables.xlsx", sheet = 4)
T20_Female_NS<-read.xlsx("data/base-life-tables.xlsx", sheet = 5)
T20_Female_S<-read.xlsx("data/base-life-tables.xlsx", sheet = 6)
T20_Male_NS<-read.xlsx("data/base-life-tables.xlsx", sheet = 7)
T20_Male_S<-read.xlsx("data/base-life-tables.xlsx", sheet = 8)

SPWL_F_NS<-read.xlsx("data/adjusted-life-tables.xlsx", sheet = 1)
SPWL_F_S_34<-read.xlsx("data/adjusted-life-tables.xlsx", sheet = 2)
SPWL_F_S_44<-read.xlsx("data/adjusted-life-tables.xlsx", sheet = 3)
SPWL_F_S_54<-read.xlsx("data/adjusted-life-tables.xlsx", sheet = 4)
SPWL_F_S_64<-read.xlsx("data/adjusted-life-tables.xlsx", sheet = 5)
SPWL_M_NS<-read.xlsx("data/adjusted-life-tables.xlsx", sheet = 6)
SPWL_M_S_34<-read.xlsx("data/adjusted-life-tables.xlsx", sheet = 7)
SPWL_M_S_44<-read.xlsx("data/adjusted-life-tables.xlsx", sheet = 8)
SPWL_M_S_54<-read.xlsx("data/adjusted-life-tables.xlsx", sheet = 9)
SPWL_M_S_64<-read.xlsx("data/adjusted-life-tables.xlsx", sheet = 10)
T20_F_NS<-read.xlsx("data/adjusted-life-tables.xlsx", sheet = 11)
T20_F_S_34<-read.xlsx("data/adjusted-life-tables.xlsx", sheet = 12)
T20_F_S_44<-read.xlsx("data/adjusted-life-tables.xlsx", sheet = 13)
T20_F_S_54<-read.xlsx("data/adjusted-life-tables.xlsx", sheet = 14)
T20_F_S_64<-read.xlsx("data/adjusted-life-tables.xlsx", sheet = 15)
T20_M_NS<-read.xlsx("data/adjusted-life-tables.xlsx", sheet = 16)
T20_M_S_34<-read.xlsx("data/adjusted-life-tables.xlsx", sheet = 17)
T20_M_S_44<-read.xlsx("data/adjusted-life-tables.xlsx", sheet = 18)
T20_M_S_54<-read.xlsx("data/adjusted-life-tables.xlsx", sheet = 19)
T20_M_S_64<-read.xlsx("data/adjusted-life-tables.xlsx", sheet = 20)

age_type_mortality<-as.matrix(read_csv("raw-mortality-data.csv"))
#Comparing model to observed mortality
plot(colnames(age_type_mortality[,10:62]), age_type_mortality[1,10:62], xlab = "Age", ylab = "Death Probability (qx)",main = "Mortality of non-smoking SPWL females")
points(SPWL_Female_NS$age, SPWL_Female_NS$qx, type = "l", col = "Red")
plot(colnames(age_type_mortality[,10:62]), age_type_mortality[2,10:62], xlab = "Age", ylab = "Death Probability (qx)",main = "Mortality of smoking SPWL females")
points(SPWL_Female_S$age, SPWL_Female_S$qx, type = "l", col = "Red")
plot(colnames(age_type_mortality[,10:62]), age_type_mortality[3,10:62], xlab = "Age", ylab = "Death Probability (qx)",main = "Mortality of non-smoking SPWL males")
points(SPWL_Male_NS$age, SPWL_Male_NS$qx, type = "l", col = "Red")
plot(colnames(age_type_mortality[,10:62]), age_type_mortality[4,10:62], xlab = "Age", ylab = "Death Probability (qx)",main = "Mortality of smoking SPWL males")
points(SPWL_Male_S$age, SPWL_Male_S$qx, type = "l", col = "Red")
plot(colnames(age_type_mortality[,1:49]), age_type_mortality[5,1:49], xlab = "Age", ylab = "Death Probability (qx)", main = "Mortality of non-smoking T20 females")
points(T20_Female_NS$age, T20_Female_NS$qx, type = "l", col = "Red")
plot(colnames(age_type_mortality[,1:49]), age_type_mortality[6,1:49], xlab = "Age", ylab = "Death Probability (qx)", main = "Mortality of smoking T20 females")
points(T20_Female_S$age, T20_Female_S$qx, type = "l", col = "Red")
plot(colnames(age_type_mortality[,1:49]), age_type_mortality[7,1:49], xlab = "Age", ylab = "Death Probability (qx)", main = "Mortality of non-smoking T20 males")
points(T20_Male_NS$age, T20_Male_NS$qx, type = "l", col = "Red")
plot(colnames(age_type_mortality[,1:49]), age_type_mortality[8,1:49], xlab = "Age", ylab = "Death Probability (qx)", main = "Mortality of smoking T20 males")
points(T20_Male_S$age, T20_Male_S$qx, type = "l", col = "Red")

#Female T20 smokers have higher mortality than male T20 smokers
plot(T20_Male_S$age, T20_Male_S$qx, type = "l", col = "Blue", xlab = "Age", ylab = "Death Probability (qx)", main = "Mortality of smoking SPWL customers by sex", ylim = c(0, 0.7), xlim = c(28,72))
points(T20_Female_S$age, T20_Female_S$qx, type = "l", col = "Red")

#Plotting the effect of smoking intervention on mortality

plot(SPWL_Female_S[1:56,]$age, SPWL_Female_S[1:56,]$qx, type = "l", col = "Red", xlim = c(37,88), main = "Mortality of SPWL females by smoking status or quitting age", xlab = "Age", ylab = "Death Probability (qx)", ylim = c(0,1))
points(SPWL_F_S_64$age, SPWL_F_S_64$qx, type = "l", col = "Orange")
points(SPWL_F_S_54$age, SPWL_F_S_54$qx, type = "l", col = "Yellow")
points(SPWL_F_S_44$age, SPWL_F_S_44$qx, type = "l", col = "Green")
points(SPWL_F_NS$age, SPWL_F_NS$qx, type = "l", col = "Blue")
legend(40,1,legend = c("Current Smoker", "55-64", "45-54", "35-44", "Non-Smoker"), col = c("red", "orange", "yellow", "green", "blue"), lty = 1,cex = 0.75)

plot(SPWL_Male_S[1:56,]$age, SPWL_Male_S[1:56,]$qx, type = "l", col = "Red", xlim = c(37,88), main = "Mortality of SPWL males by smoking status or quitting age", xlab = "Age", ylab = "Death Probability (qx)")
points(SPWL_M_S_64$age, SPWL_M_S_64$qx, type = "l", col = "Orange")
points(SPWL_M_S_54$age, SPWL_M_S_54$qx, type = "l", col = "Yellow")
points(SPWL_M_S_44$age, SPWL_M_S_44$qx, type = "l", col = "Green")
points(SPWL_M_NS$age, SPWL_M_NS$qx, type = "l", col = "Blue")
legend(40,1,legend = c("Current Smoker", "55-64", "45-54", "35-44", "Non-Smoker"), col = c("red", "orange", "yellow", "green", "blue"), lty = 1,cex = 0.75)

plot(T20_Female_S$age, T20_Female_S$qx, type = "l", col = "Red", main = "Mortality of T20 females by smoking status or quitting age", xlab = "Age", ylab = "Death Probability (qx)")
points(T20_F_S_64$age, T20_F_S_64$qx, type = "l", col = "Orange")
points(T20_F_S_54$age, T20_F_S_54$qx, type = "l", col = "Yellow")
points(T20_F_S_44$age, T20_F_S_44$qx, type = "l", col = "Green")
points(T20_F_S_34$age, T20_F_S_34$qx, type = "l", col = "Blue")
points(T20_F_NS$age, T20_F_NS$qx, type = "l", col = "Purple")
legend(30,0.5,legend = c("Current Smoker", "55-64", "45-54", "35-44","<=34","Non-Smoker"), col = c("red", "orange", "yellow", "green", "blue", "purple"), lty = 1,cex = 0.75)


plot(T20_Male_S$age, T20_Male_S$qx, type = "l", col = "Red", main = "Mortality of T20 males by smoking status or quitting age", xlab = "Age", ylab = "Death Probability (qx)")
points(T20_M_S_64$age, T20_M_S_64$qx, type = "l", col = "Orange")
points(T20_M_S_54$age, T20_M_S_54$qx, type = "l", col = "Yellow")
points(T20_M_S_44$age, T20_M_S_44$qx, type = "l", col = "Green")
points(T20_M_S_34$age, T20_M_S_34$qx, type = "l", col = "Blue")
points(T20_M_NS$age, T20_M_NS$qx, type = "l", col = "Purple")
legend(30,0.15,legend = c("Current Smoker", "55-64", "45-54", "35-44","<=34","Non-Smoker"), col = c("red", "orange", "yellow", "green", "blue", "purple"), lty = 1,cex = 0.75)


